version: 1
disable_existing_loggers: False
formatters:
  normal:
    format: "[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

root: #默認情況下配置
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: normal
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: normal
    when: midnight
    filename: ./log/daily.log
    backupCount: 30
    encoding: utf8
    interval: 1
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: normal
    filename: ./log/errors.log
    maxBytes: 5242880
    backupCount: 1
    encoding: utf8